# Generated by Django 5.0.4 on 2024-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('choice', 'Multiple Choice')], default='choice', max_length=10),
        ),
    ]
